changes done in the baseURL.
Real-Dev-Squad/website-members pull request #125
Opened 2021-02-18 03:34 UTC by aman7870

changed the base baseURL. imageURL is still same

2021-02-22 20:58 UTC, aman7870 commented
did the change in the URL and modified according to the data.

2021-02-23 09:16 UTC, sumitd94 requested changes

2021-02-23 09:16 UTC, sumitd94 commented on pages/index.js
> +    let { members } = await res.json();
We are not re-assigning `{ members }` here, let's declare it as `const`

2021-02-23 09:16 UTC, sumitd94 commented on pages/index.js
> +    });
we can convert it into a single line 
```javascript
members.sort((a, b) => (a.first_name > b.first_name) ? 1 : -1);
```

Neat, clean & readable.

2021-02-26 19:53 UTC, sumitd94 commented on jsconfig.json
> +    "experimentalDecorators": true,
Why is this changed?

2021-02-26 20:10 UTC, sumitd94 approved these changes
Thanks for the changes.

2021-02-26 20:14 UTC, merged