Fixing lint before commit using lint-staged before commit
Real-Dev-Squad/website-members pull request #201
Opened 2021-07-11 07:43 UTC by ritikrana4

Fixes lint of the staged code using lint-staged before committing.

Issue: #194

2021-07-13 12:05 UTC, sumitd94 requested changes

2021-07-13 12:05 UTC, sumitd94 commented on package.json
> +      "npm run lint-fix"
Do not fix it, check for it.

2021-07-13 12:05 UTC, sumitd94 commented on package.json
> +}
an empty line after this.

2021-07-14 12:30 UTC, ritikrana4 commented
Now will only check for lint issue.

2021-07-29 17:30 UTC, ritikrana4 commented
@sumitd94 Please review it.

2021-09-06 09:07 UTC, sumitd94 commented
#241

2021-09-06 09:07 UTC, closed without merging