Fix Card click
Real-Dev-Squad/website-members pull request #219
Opened 2021-08-08 07:34 UTC by lakshayman

2021-08-13 07:51 UTC, harshith-venkatesh approved these changes

2021-08-14 18:51 UTC, ankushdharkar requested changes

2021-08-14 18:51 UTC, ankushdharkar commented on components/member-profile/contribution/index.js
> +      onKeyDown={() => url && window.open(url, '_blank')}
```js 
onClick={goToURL}
onKeyDown={goToURL}
```

2021-08-14 18:51 UTC, ankushdharkar commented on components/member-profile/contribution/index.js
> +          <a href={url} onClick={(e) => e.stopPropagation()} target="_blank" rel="noreferrer">
We need to rethink this:

If the featureURL/URL is in members, we want to use the `<Link>`, otherwise we want to use `<a>`

2021-08-14 18:54 UTC, ankushdharkar commented on components/member-profile/contribution/index.js
> +          <a href={url} onClick={(e) => e.stopPropagation()} target="_blank" rel="noreferrer">
You should read up on client-side routing vs routing through `a` tags. This is a good starting point: https://nextjs.org/docs/routing/introduction

2021-08-16 16:33 UTC, closed without merging