added test for active-task progress
Real-Dev-Squad/website-members pull request #252
Opened 2021-09-18 13:25 UTC by thoughtlessmind

close #216

2021-10-03 15:51 UTC, Pavangbhat requested changes

2021-10-03 15:51 UTC, Pavangbhat commented on src/test/unit/components/active-task/index.test.js
> +    const percentOfTaskLeft = 100 - taskDetails.percentCompleted;
since we are using percentCompelted more than can't we destructure it?

2021-10-03 15:51 UTC, Pavangbhat commented on src/test/unit/components/active-task/index.test.js
> +      taskDetails.startedOn * 1000,
Better to destructure startedOn and endsOn since there is multiple occurance

2021-10-03 15:51 UTC, Pavangbhat commented on src/test/unit/components/active-task/index.test.js
> +    const titleEl = screen.getByText(taskDetails.title);
what does El stands for?

2021-11-05 15:35 UTC, sumitd94 approved these changes

2021-11-05 15:35 UTC, merged