updated activetask api parameter and accordion section
Real-Dev-Squad/website-members pull request #561
Opened 2023-10-13 11:17 UTC by shubhamjaintech

### What is the change?
Design Doc: https://docs.google.com/document/d/1JQ4wgYqY9cN3MLiPLpgdR_ivudZRiPPZTATb1cZGJlI/edit?usp=sharing 
1.  Task status filter API parameter updated.
2. Empty error msgs rendered if no data from api.

### Is it bug?
Yes
- Steps to repro
1. Go to members site and open any member 
https://members.realdevsquad.com/ankush 
2. Open N/W tab, you will see task status api failing.
3. On UI if end user click on accordian button then it was not expanding due to no data inside.

- Expected
API should return 200 and accordian should show error msg inside if no data returned from api.

- Actual
API gived 404.

### \*Dev Tested?

- [ ] Yes
- [ ] No

### \*Tested on:

#### Platforms

- [ ] Web

#### Browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox

### Before / After Change Screenshots
Before:
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/020d7f84-40ea-4d3d-bce7-ea5944c0c0d2)

After changes:
Desktop View:
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/8564da55-1587-407a-bb99-88dc49688344)

Mobile View:
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/096df673-0ff4-493f-ad0c-15e6a785918e)

API/N/w Tab:
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/3a1d0764-977b-4427-b985-3f0e5d6551f5)

Test Coverage:
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/6c44509d-bb30-4732-926c-d43b32ca2207)

2023-10-13 17:53 UTC, iamitprakash approved these changes

2023-10-15 22:41 UTC, Pratiyushkumar approved these changes

2023-10-16 03:31 UTC, shubhamsigdar1 requested changes
Why this changes is not under feature flag?
@shubhamjaintech I hope you remember our previous conversation...you talked with @iamitprakash or @ankushdharkar??

In staging when you raise dev to main pr...you have to fill in description
<img width="760" alt="image" src="https://github.com/Real-Dev-Squad/website-members/assets/107163260/f45a4cf5-b6d7-492a-97e4-c0e81dabda87">

2023-10-16 05:48 UTC, shubhamjaintech commented
@shubhamsigdar1 
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/4a8b38fc-4d28-4998-8f6d-c022745c2831)
I remember asking tejas yesterday, please refer above screenshot.
Meanwhile today morning, i got email that 2nd approval also approved this bug fix change, so i requested for review/merge? 

@iamitprakash can you please guide/confirm that do we need a feature flag for it or not?  Thank you.

**My view of not keeping it behind feature flag as its a small bug fix and no major impact on other modules?  if team feel otherwise, please let me know i will try to add it behind feature flag.  Thank you.

2023-10-16 17:20 UTC, shubhamjaintech commented
Unit Testing:
A. Feature flag  ?dev=true
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/3d93a632-ad7c-457f-b5c4-f626348b3095)

B.  Feature flag false
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/d629b2f6-84af-4883-ba09-e52acb0d4a17)

2023-10-16 18:13 UTC, shubhamsigdar1 approved these changes

2023-10-18 04:09 UTC, merged