open links in a new tab
Real-Dev-Squad/website-members pull request #75
Opened 2020-11-23 11:25 UTC by tejasberi

2020-12-03 20:34 UTC, whyDontI requested changes

2020-12-03 20:34 UTC, whyDontI commented on components/member-profile/index.js
> +                  fillRule="evenodd"
Please revert this to `fill-rule`.

2020-12-03 20:34 UTC, whyDontI commented on components/member-profile/index.js
> +                  fillRule="evenodd"
Please revert this to `fill-rule`.

2021-01-01 10:58 UTC, closed without merging

2021-01-01 10:58 UTC, tejasberi commented
closing