Fetching user PRs using SSR
Real-Dev-Squad/website-members pull request #99
Opened 2021-01-18 07:39 UTC by Rucha1499

The PR details are now being rendered on server side. Fixes #92

2021-01-18 08:30 UTC, sumitd94 requested changes

2021-01-18 08:30 UTC, sumitd94 commented on components/member-profile/index.js
>    const { membersData } = props;
Could you please remove this line of code, I think this is not needed since we are destructuring on line no 9.

2021-01-18 11:53 UTC, sumitd94 commented on components/member-profile/index.js
>    const { membersData } = props;
Sorry My bad, this line of code is also required. On line no 9 we are not completely destruturing the object. There are social media links also included in this `membersData`
I will improve this code in my refactor task.

2021-01-18 11:55 UTC, sumitd94 approved these changes
Thank you for the changes. Good job !

2021-01-19 09:10 UTC, swarajpure approved these changes
Great job in there!

Thank you! 😄

2021-01-19 09:11 UTC, merged